# Generated by Django 3.1.7 on 2021-04-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='ReceivedMessage',
        ),
        migrations.AlterModelOptions(
            name='receivedmessage',
            options={'verbose_name': 'Message'},
        ),
    ]
