# Generated by Django 3.1.7 on 2021-04-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(max_length=254, unique=True)),
                ('intro', models.TextField()),
                ('section_one', models.TextField()),
                ('section_two', models.TextField(blank=True, null=True)),
                ('section_three', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('original_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('credit', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=254, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
            },
        ),
    ]
